//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBiKEY.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterDependencyView
    {
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public int CharacterID { get; set; }
        public string CharacterCode { get; set; }
        public string CharacterDescription { get; set; }
        public int CharacterStateID { get; set; }
        public string CharacterStateCode { get; set; }
        public string CharacterStateDescription { get; set; }
        public int DisabledCharacterID { get; set; }
        public string DisabledCharacterCode { get; set; }
        public string DisabledCharacterDescription { get; set; }
        public int DisabledCategoryID { get; set; }
        public string DisabledCategoryName { get; set; }
    }
}
