//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBiKEY.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class CharacterState
    {
        public CharacterState()
        {
            this.DisabledCharacters = new HashSet<Character>();
            this.Species = new HashSet<Species>();
        }
    
        public int CharacterStateID { get; set; }
        public int CharacterID { get; set; }
        public string CharacterStateCode { get; set; }
        public string CharacterStateDescription { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual ICollection<Character> DisabledCharacters { get; set; }
        public virtual ICollection<Species> Species { get; set; }
    }
}
