//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBiKEY.Application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InteractiveKeyEntities : DbContext
    {
        public InteractiveKeyEntities()
            : base("name=InteractiveKeyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CharacterCategory> CharacterCategories { get; set; }
        public DbSet<Species> Species { get; set; }
        public DbSet<Character> Characters { get; set; }
        public DbSet<CharacterState> CharacterStates { get; set; }
        public DbSet<CharacterDependencyView> CharacterDependencyViews { get; set; }
        public DbSet<CharacterStateView> CharacterStateViews { get; set; }
        public DbSet<UploadedFile> UploadedFiles { get; set; }
    }
}
