//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBiKEY.Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class Species
    {
        public Species()
        {
            this.CharacterStates = new HashSet<CharacterState>();
        }
    
        public int SpeciesID { get; set; }
        public string SpeciesName { get; set; }
        public byte[] DescriptionFile { get; set; }
        public string DescriptionFileName { get; set; }
    
        public virtual ICollection<CharacterState> CharacterStates { get; set; }
    }
}
